//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_kumo_eip0001model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BizExTracker
    {
        public int Id { get; set; }
        public int VenderId { get; set; }
        public string ExpenseName { get; set; }
        public int ExpenseCategoryId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int PaymentModeId { get; set; }
        public string InvoiceNumber { get; set; }
        public int PaidBy { get; set; }
        public bool PaidByCompany { get; set; }
        public string ChequeNumber { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ExpenseCategory ExpenseCategory { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
