//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_kumo_eip0001model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Contacts = new HashSet<Contact>();
            this.RevenueTrackers = new HashSet<RevenueTracker>();
        }
    
        public int Id { get; set; }
        public string Website { get; set; }
        public string FaxNumber { get; set; }
        public string CompanyAddress { get; set; }
        public string Phone { get; set; }
        public int AssignedTo { get; set; }
        public string CustomerId { get; set; }
        public string CompanyName { get; set; }
        public int IndustryId { get; set; }
        public string CompanyEmailAddress { get; set; }
        public int SourceTypeId { get; set; }
        public int LeadTypeId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual LeadType LeadType { get; set; }
        public virtual SourceType SourceType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<RevenueTracker> RevenueTrackers { get; set; }
    }
}
