//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_kumo_eip0001model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.Document1 = new HashSet<Document>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Extension { get; set; }
        public int ItemType { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public string Uuid { get; set; }
        public Nullable<long> FileSize { get; set; }
        public int DocumentLibraryId { get; set; }
        public string BlobUrl { get; set; }
        public System.DateTime Modified { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual DocumentLibrary DocumentLibrary { get; set; }
        public virtual ICollection<Document> Document1 { get; set; }
        public virtual Document Document2 { get; set; }
    }
}
