//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_kumo_eip0001model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.BizExTrackers = new HashSet<BizExTracker>();
            this.Customers = new HashSet<Customer>();
            this.EmergencyContacts = new HashSet<EmergencyContact>();
            this.Employees = new HashSet<Employee>();
            this.EmployeeSensitives = new HashSet<EmployeeSensitive>();
            this.Events = new HashSet<Event>();
            this.Meetings = new HashSet<Meeting>();
            this.Projects = new HashSet<Project>();
            this.SalaryTrackers = new HashSet<SalaryTracker>();
            this.Tours = new HashSet<Tour>();
        }
    
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Fullname { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string IdentificationNumber { get; set; }
        public int IdentityType { get; set; }
        public string MobileNumber { get; set; }
        public string WorkNumber { get; set; }
        public string HomeNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string EmployeeId { get; set; }
        public int JobTitleId { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<int> LineManagerId { get; set; }
        public int EmploymentStatusId { get; set; }
        public bool Current { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> TerminaiondDate { get; set; }
        public int WorkPassTypeId { get; set; }
        public Nullable<System.DateTime> WorkPassExpiryDate { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public string UserId { get; set; }
        public decimal Salary { get; set; }
        public int PaymentFrequencyId { get; set; }
        public int PaymentModeId { get; set; }
        public int BankId { get; set; }
        public string AccountName { get; set; }
        public string MedicalIsuranceNumber { get; set; }
        public int HighestQualificationId { get; set; }
        public string Skills { get; set; }
        public string EmergencyContactFirstName { get; set; }
        public string EmergencyContactLastName { get; set; }
        public string EmergencyContactFullName { get; set; }
        public string EmergencyContactMobileNumber { get; set; }
        public string EmergencyContactWorkNumber { get; set; }
        public string EmergencyContactEmailAddress { get; set; }
        public int EmergencyContactRelationshipId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual ICollection<BizExTracker> BizExTrackers { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<EmergencyContact> EmergencyContacts { get; set; }
        public virtual EmploymentStatus EmploymentStatus { get; set; }
        public virtual IdentityType IdentityType1 { get; set; }
        public virtual JobTitle JobTitle { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual Employee Manager { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual PaymentFrequency PaymentFrequency { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual Qualification Qualification { get; set; }
        public virtual WorkPassType WorkPassType { get; set; }
        public virtual ICollection<EmployeeSensitive> EmployeeSensitives { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Meeting> Meetings { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<SalaryTracker> SalaryTrackers { get; set; }
        public virtual ICollection<Tour> Tours { get; set; }
        public virtual Relationship Relationship { get; set; }
    }
}
