//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_kumo_eip0001model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSensitive
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public string IdentificationNumber { get; set; }
        public int IdentityTypeId { get; set; }
        public string EmergencyContactFirstName { get; set; }
        public string EmergencyContactLastName { get; set; }
        public string EmergencyContactFullName { get; set; }
        public string EmergencyContactMobileNumber { get; set; }
        public string EmergencyContactWorkNumber { get; set; }
        public string EmergencyContactEmailAddress { get; set; }
        public int EmergencyContactRelationship { get; set; }
        public int EmploymentStatusId { get; set; }
        public bool Current { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime TerminationDate { get; set; }
        public int WorkPassTypeId { get; set; }
        public System.DateTime WorkPassExpiryDate { get; set; }
        public decimal Salary { get; set; }
        public int PaymentFrequencyId { get; set; }
        public int PaymentModeId { get; set; }
        public int BankTypeId { get; set; }
        public string AccountNameOrNumber { get; set; }
        public string MedicalInsuranceNumber { get; set; }
        public int HighestQualificationId { get; set; }
        public string Skills { get; set; }
    
        public virtual BankType BankType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual EmploymentStatus EmploymentStatus { get; set; }
        public virtual IdentityType IdentityType { get; set; }
        public virtual PaymentFrequency PaymentFrequency { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual Qualification Qualification { get; set; }
        public virtual Relationship Relationship { get; set; }
        public virtual WorkPassType WorkPassType { get; set; }
    }
}
