//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_kumo_eip0001model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Payment()
        {
            this.RevenueTrackers = new HashSet<RevenueTracker>();
        }
    
        public int Id { get; set; }
        public string PaymentNumber { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal AmountReceived { get; set; }
        public int PaymentModeId { get; set; }
        public string ChequeNumber { get; set; }
        public int BankTypeId { get; set; }
        public string PaymentStatus { get; set; }
    
        public virtual BankType BankType { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual ICollection<RevenueTracker> RevenueTrackers { get; set; }
    }
}
