//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_kumo_eip0001model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryTracker
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal BasicSalary { get; set; }
        public decimal Commission { get; set; }
        public double TotalNumberOfHours { get; set; }
        public decimal CPFContribution { get; set; }
        public string WorkerLevy { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
