//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_kumo_eip0001model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAction
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int ActionId { get; set; }
        public int ComponentId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Component Component { get; set; }
        public virtual SystemAction SystemAction { get; set; }
    }
}
