CREATE TABLE [dbo].[EmployeeSensitive]
(
	[Id]            INT            IDENTITY (1, 1) NOT NULL,
	[EmployeeId] [int] NOT NULL,
	[DateofBirth] DATETIME NOT NULL,
	[IdentificationNumber] NVARCHAR(50) NOT NULL,
	[IdentityTypeId] INT NOT NULL,
	[EmergencyContactFirstName] NVARCHAR(255) NOT NULL,
	[EmergencyContactLastName] NVARCHAR(255) NOT NULL,
	[EmergencyContactFullName] NVARCHAR(500) NOT NULL,
	[EmergencyContactMobileNumber] NVARCHAR(50) NOT NULL,
	[EmergencyContactWorkNumber] NVARCHAR(100) NOT NULL,
	[EmergencyContactEmailAddress] NVARCHAR(255) NOT NULL,
	[EmergencyContactRelationship] INT NOT NULL,
	[EmploymentStatusId] [int] NOT NULL,
	[Current] BIT NOT NULL,
	[EffectiveDate] DATETIME NOT NULL,
	[EndDate] DATETIME NOT NULL,
	[TerminationDate] DATETIME NOT NULL,
	[WorkPassTypeId] INT NOT NULL,
	[WorkPassExpiryDate] DATETIME NOT NULL,
	[Salary] DECIMAL(18, 2) NOT NULL,
	[PaymentFrequencyId] INT NOT NULL,
	[PaymentModeId] INT NOT NULL,
	[BankTypeId] INT NOT NULL,
	[AccountNameOrNumber] NVARCHAR(500) NOT NULL,
	[MedicalInsuranceNumber] NVARCHAR(100) NOT NULL,
	[HighestQualificationId] INT NOT NULL,
	[Skills] NVARCHAR(500) NOT NULL,
	PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_EmployeeSensitive_IdentityType] FOREIGN KEY ([IdentityTypeId]) REFERENCES [dbo].[IdentityTypes] ([Id]),
    CONSTRAINT [FK_EmployeeSensitive_Employee] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[Employee] ([Id]),
	CONSTRAINT [FK_EmployeeSensitive_Relationship] FOREIGN KEY ([EmergencyContactRelationship]) REFERENCES [dbo].[Relationships] ([Id]),
    CONSTRAINT [FK_EmployeeSensitive_EmploymentStatus] FOREIGN KEY ([EmploymentStatusId]) REFERENCES [dbo].[EmploymentStatuses] ([Id]),
	CONSTRAINT [FK_EmployeeSensitive_WorkPassTypes] FOREIGN KEY ([WorkPassTypeId]) REFERENCES [dbo].[WorkPassTypes] ([Id]),
    CONSTRAINT [FK_EmployeeSensitive_PaymentFrequency] FOREIGN KEY ([PaymentFrequencyId]) REFERENCES [dbo].[PaymentFrequencies] ([Id]),
	CONSTRAINT [FK_EmployeeSensitive_PaymentModes] FOREIGN KEY ([PaymentModeId]) REFERENCES [dbo].[PaymentModes] ([Id]),
    CONSTRAINT [FK_EmployeeSensitive_BankTypes] FOREIGN KEY ([BankTypeId]) REFERENCES [dbo].[BankTypes] ([Id]),
	CONSTRAINT [FK_EmployeeSensitive_Qualitifications] FOREIGN KEY ([HighestQualificationId]) REFERENCES [dbo].[Qualifications] ([Id])
)
