//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUMO.CentralAdmin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.EIPUsers = new HashSet<EIPUser>();
        }
    
        public int Id { get; set; }
        public string ClientName { get; set; }
        public string DBName { get; set; }
        public string DBUser { get; set; }
        public string DBPassword { get; set; }
        public string DBServer { get; set; }
        public string Status { get; set; }
        public string SiteUrl { get; set; }
        public string ActiveComponents { get; set; }
        public string DeploymentLogs { get; set; }
        public Nullable<System.DateTime> DeployedDate { get; set; }
    
        public virtual ICollection<EIPUser> EIPUsers { get; set; }
    }
}
