var ns = sfe.ns('sfe.routes');

ns.routeConfiguration = [
    // --------------------------- TOP LEVEL ------------------------------------
    {
        state: 'home',
        route: '/Home',
        displayName: 'KUMO',
        inTopnav: true,
        parentState: undefined,
        doesLink: true,
    },
    {
        state: 'usermanagement',
        route: '/Account',
        displayName: 'User Management',
        inTopnav: true,
        parentState: undefined,
        doesLink: true,
    },
    //{
    //    state: 'alluser',
    //    route: '/Account',
    //    displayName: 'All users',
    //    inTopnav: true,
    //    parentState: 'usermanagement',
    //    doesLink: true,
    //},
    //{
    //    state: 'addaccount',
    //    route: '/Account/Register',
    //    displayName: 'Add user',
    //    inTopnav: true,
    //    parentState: 'usermanagement',
    //    doesLink: true,
    //},
    {
        state: 'hr',
        route: '/hr',
        displayName: 'HR',
        inTopnav: true,
        parentState: undefined,
        doesLink: true,
    },
    // {
    //     state: 'allemployees',
    //     route: '/Employees',
    //     displayName: 'All employees',
    //     inTopnav: true,
    //     parentState: 'hr',
    //     doesLink: true,
    // },
    //{
    //    state: 'addemployee',
    //    route: '/Employees/Create',
    //    displayName: 'Add employee',
    //    inTopnav: true,
    //    parentState: 'hr',
    //    doesLink: true,
    //},
    {
        state: 'crm',
        route: '/crm',
        displayName: 'CRM',
        inTopnav: true,
        parentState: undefined,
        doesLink: true,
    },
     {
         state: 'erp',
         route: '/erp/Calendar',
         displayName: 'ERP',
         inTopnav: true,
         parentState: undefined,
         doesLink: true,
     },

    {
        state: 'mis',
        route: '/mis',
        displayName: 'MIS',
        inTopnav: true,
        parentState: undefined,
        doesLink: true,
    },
    // {
    //     state: 'allcustomers',
    //     route: '/Customers',
    //     displayName: 'All customers',
    //     inTopnav: true,
    //     parentState: 'crm',
    //     doesLink: true,
    // },
    //{
    //    state: 'addcustomer',
    //    route: '/Customers/Create',
    //    displayName: 'Add customer',
    //    inTopnav: true,
    //    parentState: 'crm',
    //    doesLink: true,
    //},
]