//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_kumo_eip0001model.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HRMResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HRMResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("test_kumo_eip0001model.Resources.HRMResources", typeof(HRMResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name or Number.
        /// </summary>
        public static string AccountNameorNumber {
            get {
                return ResourceManager.GetString("AccountNameorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DateofBirth {
            get {
                return ResourceManager.GetString("DateofBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        public static string EffectiveDate {
            get {
                return ResourceManager.GetString("EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        public static string EmployeeID {
            get {
                return ResourceManager.GetString("EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment Status.
        /// </summary>
        public static string EmploymentStatus {
            get {
                return ResourceManager.GetString("EmploymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Qualification.
        /// </summary>
        public static string HighestQualification {
            get {
                return ResourceManager.GetString("HighestQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Address.
        /// </summary>
        public static string HomeAddress {
            get {
                return ResourceManager.GetString("HomeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Number.
        /// </summary>
        public static string HomeNumber {
            get {
                return ResourceManager.GetString("HomeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification Number.
        /// </summary>
        public static string IdentificationNumber {
            get {
                return ResourceManager.GetString("IdentificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Type.
        /// </summary>
        public static string IdentityType {
            get {
                return ResourceManager.GetString("IdentityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Manager.
        /// </summary>
        public static string LineManager {
            get {
                return ResourceManager.GetString("LineManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Isurance Number.
        /// </summary>
        public static string MedicalIsuranceNumber {
            get {
                return ResourceManager.GetString("MedicalIsuranceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pament Frequency.
        /// </summary>
        public static string PamentFrequency {
            get {
                return ResourceManager.GetString("PamentFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Mode.
        /// </summary>
        public static string PaymentMode {
            get {
                return ResourceManager.GetString("PaymentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture.
        /// </summary>
        public static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        public static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination Date.
        /// </summary>
        public static string TerminationDate {
            get {
                return ResourceManager.GetString("TerminationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Number.
        /// </summary>
        public static string WorkNumber {
            get {
                return ResourceManager.GetString("WorkNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Pass Expiry Date.
        /// </summary>
        public static string WorkPassExpiryDate {
            get {
                return ResourceManager.GetString("WorkPassExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Pass Type.
        /// </summary>
        public static string WorkPassType {
            get {
                return ResourceManager.GetString("WorkPassType", resourceCulture);
            }
        }
    }
}
